# https://docs.docker.com/cloud/ecs-integration/

version: '3.8'
services:
  substrate:
    image: prosopo/substrate:demo-v1.0.0
    ports:
      - "9615:9615"
      - "9944:9944"
      - "9933:9933"
    deploy:
      replicas: 1
  database:
    image: mongo:5.0.4
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=prosopo
  # provider:
  #   image: prosopo/provider:demo-v1.0.0
  #   ports:
  #     - "3000:3000"
  #     - "4000:4000"
  #   depends_on:
  #     - substrate-node
  #     - provider-db
  #   deploy:
  #     replicas: 1

x-aws-vpc: vpc-0d475f14c1385d682
x-aws-loadbalancer: arn:aws:elasticloadbalancing:eu-west-1:333775583992:loadbalancer/net/demo-net/c964b999910c2e7d
x-aws-cloudformation:
  Resources:
    # CloudMap:
    #   Properties:
    #     Description: Service Map for Docker Compose project integration
    #     Name: integration.local
    #     # Vpc: vpc-0d475f14c1385d682
    #   Type: AWS::ServiceDiscovery::PublicDnsNamespace
    SubstrateTCP9944Listener:
      Properties:
        Certificates:
          - CertificateArn: "arn:aws:acm:eu-west-1:333775583992:certificate/4566efed-fb66-498b-82d0-73be97a42191"
        Protocol: TLS
        Port: 9944
    SubstrateTCP9933Listener:
      Properties:
        Certificates:
          - CertificateArn: "arn:aws:acm:eu-west-1:333775583992:certificate/4566efed-fb66-498b-82d0-73be97a42191"
        Protocol: TLS
        Port: 9933
