version: '3.4'
services:
  provider-db:
    image: ${DATABASE_IMAGE}
    volumes:
      - ${DATABASE_SHARED_VOLUME_PATH}:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
  substrate-node:
    image: prosopo/substrate:demo-v1.0.0
    ports:
      - "9615:9615"
      - "9944:9944"
      - "9933:9933"
