version: '3.4'
services:
  contracts:
    image: paritytech/contracts-ci-linux:latest
    volumes:
      - type: bind
        source: ./protocol
        target: /usr/src/protocol
      - type: bind
        source: ./dapp-example
        target: /usr/src/dapp-example
      - type: bind
        source: ./docker
        target: /usr/src/docker
    command: "tail -f /dev/null"
    links:
      - substrate-node
  provider-api:
    build:
      context: .
      dockerfile: ./docker/dev.dockerfile
    volumes:
      - type: bind
        source: .
        target: /usr/src/
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    links:
      - substrate-node
      - provider-db
    extra_hosts:
      - "host.docker.internal:host-gateway"
  provider-db:
    image: ${DATABASE_IMAGE}
    volumes:
      - ./db/:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
  substrate-node:
    image: prosopo/substrate:v0.14.0
    build:
      context: ./docker/
      dockerfile: Substrate.dockerfile
    ports:
      - "9615:9615"
      - "9944:9944"
      - "9933:9933"
