version: '3.4'
services:
  substrate-node:
    image: prosopo/substrate:demo-v1.0.0
    ports:
      - "9615:9615"
      - "9944:9944"
      - "9933:9933"
    deploy:
      replicas: 1
  provider:
    image: prosopo/provider
    ports:
      - "3000:3000"
      - "4000:4000"
    deploy:
      replicas: 1
