apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o deployment/
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: protocol-build
  name: protocol-build
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: protocol-build
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o deployment/
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: protocol-build
    spec:
      containers:
        - image: prosopo/protocol-build:latest
          name: protocol-build
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/protocol
              name: protocol-build-claim0
      restartPolicy: Always
      volumes:
        - name: protocol-build-claim0
          persistentVolumeClaim:
            claimName: protocol-build-claim0
status: {}
