apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o deployment/
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: provider-db
  name: provider-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: provider-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o deployment/
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: provider-db
    spec:
      containers:
        - image: provider-db
          name: provider-db
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: provider-db-claim0
      restartPolicy: Always
      volumes:
        - name: provider-db-claim0
          persistentVolumeClaim:
            claimName: provider-db-claim0
status: {}
