apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o deployment/
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: substrate-node
  name: substrate-node
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: substrate-node
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o deployment/
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: substrate-node
    spec:
      containers:
        - image: prosopo/substrate:v0.14.0
          name: substrate-node
          ports:
            - containerPort: 9615
            - containerPort: 9944
            - containerPort: 9933
          resources: {}
      restartPolicy: Always
status: {}
